#include <iostream>

int main() try
{

	system("pause");
	return 0;
}
catch (std::exception& _E) { throw _E; }